feat: разработать функционал согласно ТЗ 16
galievranis/java-shareit pull request #5
Opened 2023-05-20 14:40 UTC by galievranis

2023-05-21 19:33 UTC, zgreen3 requested changes
Привет.
Проверил проект, он соответствует ТЗ, отлично!
После принятия к сведению комментариев "Можно лучше" и "Для информации" присылай работу на завершение проверки.
Спасибо.

2023-05-21 19:33 UTC, zgreen3 commented on docker-compose.yml
> +version: '3.8'
Отлично:
Вижу, что ты разобрался в теме объединения ряда докер образов в единой docker-compose конфигурации. 
Это точно пригодится тебе не раз в будущих рабочих проектах (на базе микросервисной и т.н. SOA-архитектуре).

+Небольшой доп. комментарий, для информации, про текущую (по состоянию на май 2023 г.)) ситуацию с docker-compose API:
Поддержка Compose версии 1 (Docker Compose V1) больше не будет предоставляться после июня 2023 года и будет удалена из всех будущих версий Docker для всех основных ОС (Windows, Mac, Unix-like),
источник - https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/
Там ничего радикально не изменится с т.з. пользователей docker-compose (т.е. с т.з. разработчиков в основном это многочисленные улучшения процесса сборки compose-системы из докер-образов). 
Самое существенное для пользователей - теперь вызов compose будет осуществляться в командной строке так "docker compose" а не как раньше, "docker-compose" =), источник - https://docs.docker.com/compose/migrate/#:~:text=Compose%20V1%20no%20longer%20receives,Docker%20Desktop%20after%20June%202023.

2023-05-21 19:33 UTC, zgreen3 commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
Отлично:
Хорошо, что параметры доступа к сервису `shareIt-server` здесь соответствуют параметрам в `docker-compose.yml` файле (как и порт самого сервера сервиса  `shareIt-gateway` выше) / не изменены по сравнению с предложенными в шаблоне из ТЗ (https://github.com/yandex-praktikum/java-shareit/blob/add-docker/gateway/src/main/resources/application.properties). 

Важно иногда вспоминать про эту неявную связь настроект docker compose и параметров из данного файла application.properties, в случаях, когда нужно разобрать причины какой-либо ошибки доступа к серверу.

2023-05-21 19:33 UTC, zgreen3 commented on server/src/main/resources/application.properties
>  spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
Для информации:

Такой вариант задания url здесь вполне допустим и корректен.
 
При этом важно иметь ввиду, что при запуске docker-compose конфигурации, это свойство (url) будет перезаписано тем, которое указано в docker-compose.yml файле 
(по правилам конвертации переменной окружения из docker-compose.yml файла - шире из окружения, environment, уровня ОС - в свойства проекта Spring Boot, см. описание этого здесь, 
https://stackoverflow.com/questions/73584692/spring-boot-application-properties-variable-conversion-matching-when-retrieved-f , в частности, о приоритете переменных окружения над свойствами из файла application.properties, здесь, https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/features.html#features.external-config , и о правилах трансформации этих переменных в эти свойства в Spring Boot, здесь, https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables).

Также (для лучшего ориентирования в причинах указания тех или иных настроек в разных местах проекта) важно понимать, почему в файле docker-compose.yml указан другой url адрес, отличный от указанного в application.properties: дело в том, что все докер-контейнеры, запущенные в одном docker-compose файле, работают по умолчанию в одной виртуальной сети, где их сервера имеют доменные имена по имени самих сервисов, указанных в этом файле, см., например, упоминание об этом тут, https://stackoverflow.com/a/66171015.

2023-05-21 19:33 UTC, zgreen3 commented on gateway/Dockerfile
> +ENTRYPOINT ["java","-jar","/gateway.jar"]
Отлично:

Отлично, вижу, что ты разобрался в создании базовых докер-файлов, на основе которых можно запускать (независимо от docker-compose.yml файла) докер-образ из контейнера, описанного здесь!
В рабочих проектах это бывает полезно как для отладки какого-либо отдельного сервиса в микросервисной архитектуре, так и для создания целых интергационных тестов (например, на основе фреймворка Testcontainers, https://www.testcontainers.org/ , прямо в коде Java, в тестовых классах)!

2023-05-21 19:33 UTC, zgreen3 commented on server/src/main/resources/application.properties
>  #---
Для информации:

Такие разделители-комментарии не случайны в этом файле, они задают множество вариантов настроек в едином документе (см., например, детали, тут, https://docs.spring.io/spring-boot/docs/3.0.0-M4/reference/htmlsingle/#features.external-config.files.multi-document ).

2023-05-21 19:33 UTC, zgreen3 commented on pom.xml
Можно лучше:

Понимаю, что зависимость spring-boot-starter-validation попала в этот общий pom-файл, скорее всего, из проекта-образца из ТЗ, при этом, она здесь, насколько могу судить, не требуется, т.к. аналогичная зависимость есть в pom-файле проекта gateway, а для проекта server она в соответствии с ТЗ уже не нужна.

2023-05-21 19:33 UTC, zgreen3 commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    protected ResponseEntity<Object> delete(String path, long userId) {
Можно лучше:

Как подсказывает IDE, этот метод нигде не используется и может быть удалён как лишний код, следуя принципу YAGNI (https://ru.wikipedia.org/wiki/YAGNI).

2023-05-21 19:33 UTC, zgreen3 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +public class BookingController {
Отлично:

Вижу, что валидация на уровне всех контроллеров, с которыми непосредственно работают пользователи (а также добавлена требующаяся при этом обработка исключений), корректно вынесена в данный сервис gateway, в т.ч. добавлены недостающие в проекте-образце из ТЗ методы-эндпоинты в контроллер BookingController - всё в полном соответствии с ТЗ!

2023-05-21 19:33 UTC, zgreen3 commented on gateway/src/main/java/ru/practicum/shareit/util/validator/start/CheckDateValidator.java
> +    public void initialize(StartBeforeEndDateValid constraintAnnotation) {
Отлично:

Здорово, что реализовал здесь не самую очевидную (в части написания) пользовательскую валидацию на основе ConstraintValidator!

Могу ошибаться, но мне кажется, что метод initialize ничего не переопределяет в родительском методе, а значит можно попробовать обойтись здесь без него (в стремлении не усложнять проект больше, чем необходимо).

2023-05-22 02:59 UTC, galievranis commented on docker-compose.yml
> +version: '3.8'
Принял к сведению, спасибо. Ну мы на теории собирали через docker compose, у меня как раз вторая версия и стоит в настройках докера)

2023-06-02 17:57 UTC, merged